### PR TITLE
46 header nav max width instead of fluid

### PR DESCRIPTION
**Pull request by willbreitkreutz**
Make it so you can pass a `fluidNav` prop to the SiteWrapper component.  If fluid, then full width, otherwise the default is the constrained width of the `Container` element (1140px I believe)

### CODE REVIEW

**Comment by adamscarberry** [comment]
The banner at the top will need to have a max width too.

image



Do you prefer specifying the max width in pixels vs `gw-max-w-screen-2xl` which equals `1536px`.
 https://tailwindcss.com/docs/max-width

**Comment by willbreitkreutz** [comment]
@adamscarberry I'll give the banner a shot, I did it in px because i copied it from somewhere else....

**Comment by adamscarberry** [comment]
@willbreitkreutz ok.  If you have no opjections, I would like to use `gw-max-w-screen-2xl` for the limited width and `w-full` for the fluid.

For reference `w-full` = `width: 100%;` where as `w-screen` = `width: 100vw;`.  I'm not sure which is better at the moment.

**Comment by willbreitkreutz** [comment]
`w-full` will honor any sizes set above it in the tree, `w-screen` will look at the actual viewport size...

I'll update the classes to use the tailwind classes

**Comment by willbreitkreutz** [comment]
@adamscarberry ready for review

**Review by adamscarberry — APPROVED** [review]
This looks great.  Thanks @willbreitkreutz !

**Pull request merged**
