### PR TITLE
29 add more content under getting started

### PR DESCRIPTION
**Pull request by willbreitkreutz**
Added some docs for a quick start, adding tailwind and adding redux-bundler for routing.  If we want to add other routing options or whatever, we can over time.

### CODE REVIEW

**Review by jbkolze — APPROVED** [review]
Didn't run through the whole guide by hand, but skimmed the docs and everything looked good to me.  Should be a good intro for someone trying to get started from step one.

**Comment by willbreitkreutz** [comment]
I keep adding `referrer="no-referrer"` instead of `rel="no-referrer"` to links like a dummy

**Review by adamscarberry — APPROVED** [review]
Looks good.  

Reminder that the `base` config variable in vite.config.js is needed for WM websites, but realize that groundwork is for more general usage.

**Comment by willbreitkreutz** [comment]
@adamscarberry yeah, was thinking about adding that, but might do it as another page, maybe add an advanced section or something.

**Pull request merged**
